#ifndef QCCE_BITBOARD_H_
#define QCCE_BITBOARD_H_

#include "types.h"

#define QCCE_UNIVERSAL_BITBOARD (-1ull)

#define QCCE_RANK_8_BITBOARD (0b11111111ull)
#define QCCE_RANK_7_BITBOARD (QCCE_RANK_8_BITBOARD << 8)
#define QCCE_RANK_6_BITBOARD (QCCE_RANK_7_BITBOARD << 8)
#define QCCE_RANK_5_BITBOARD (QCCE_RANK_6_BITBOARD << 8)
#define QCCE_RANK_4_BITBOARD (QCCE_RANK_5_BITBOARD << 8)
#define QCCE_RANK_3_BITBOARD (QCCE_RANK_4_BITBOARD << 8)
#define QCCE_RANK_2_BITBOARD (QCCE_RANK_3_BITBOARD << 8)
#define QCCE_RANK_1_BITBOARD (QCCE_RANK_2_BITBOARD << 8)
#define QCCE_RANK_87_BITBOARD (QCCE_RANK_8_BITBOARD | QCCE_RANK_7_BITBOARD)
#define QCCE_RANK_21_BITBOARD (QCCE_RANK_2_BITBOARD | QCCE_RANK_1_BITBOARD)

#define QCCE_FILE_A_BITBOARD (0b100000001000000010000000100000001000000010000000100000001ull)
#define QCCE_FILE_B_BITBOARD (QCCE_FILE_A_BITBOARD << 1)
#define QCCE_FILE_C_BITBOARD (QCCE_FILE_B_BITBOARD << 1)
#define QCCE_FILE_D_BITBOARD (QCCE_FILE_C_BITBOARD << 1)
#define QCCE_FILE_E_BITBOARD (QCCE_FILE_D_BITBOARD << 1)
#define QCCE_FILE_F_BITBOARD (QCCE_FILE_E_BITBOARD << 1)
#define QCCE_FILE_G_BITBOARD (QCCE_FILE_F_BITBOARD << 1)
#define QCCE_FILE_H_BITBOARD (QCCE_FILE_G_BITBOARD << 1)
#define QCCE_FILE_AB_BITBOARD (QCCE_FILE_A_BITBOARD | QCCE_FILE_B_BITBOARD)
#define QCCE_FILE_GH_BITBOARD (QCCE_FILE_G_BITBOARD | QCCE_FILE_H_BITBOARD)

#define QCCE_NOT_RANK_8_BITBOARD (~QCCE_RANK_8_BITBOARD)
#define QCCE_NOT_RANK_7_BITBOARD (~QCCE_RANK_7_BITBOARD)
#define QCCE_NOT_RANK_6_BITBOARD (~QCCE_RANK_6_BITBOARD)
#define QCCE_NOT_RANK_5_BITBOARD (~QCCE_RANK_5_BITBOARD)
#define QCCE_NOT_RANK_4_BITBOARD (~QCCE_RANK_4_BITBOARD)
#define QCCE_NOT_RANK_3_BITBOARD (~QCCE_RANK_3_BITBOARD)
#define QCCE_NOT_RANK_2_BITBOARD (~QCCE_RANK_2_BITBOARD)
#define QCCE_NOT_RANK_1_BITBOARD (~QCCE_RANK_1_BITBOARD)
#define QCCE_NOT_RANK_87_BITBOARD (~QCCE_RANK_87_BITBOARD)
#define QCCE_NOT_RANK_21_BITBOARD (~QCCE_RANK_21_BITBOARD)

#define QCCE_NOT_FILE_A_BITBOARD (~QCCE_FILE_A_BITBOARD)
#define QCCE_NOT_FILE_B_BITBOARD (~QCCE_FILE_B_BITBOARD)
#define QCCE_NOT_FILE_C_BITBOARD (~QCCE_FILE_C_BITBOARD)
#define QCCE_NOT_FILE_D_BITBOARD (~QCCE_FILE_D_BITBOARD)
#define QCCE_NOT_FILE_E_BITBOARD (~QCCE_FILE_E_BITBOARD)
#define QCCE_NOT_FILE_F_BITBOARD (~QCCE_FILE_F_BITBOARD)
#define QCCE_NOT_FILE_G_BITBOARD (~QCCE_FILE_G_BITBOARD)
#define QCCE_NOT_FILE_H_BITBOARD (~QCCE_FILE_H_BITBOARD)
#define QCCE_NOT_FILE_AB_BITBOARD (~QCCE_FILE_AB_BITBOARD)
#define QCCE_NOT_FILE_GH_BITBOARD (~QCCE_FILE_GH_BITBOARD)

#define QCCE_NOT_RANK_8_FILE_AB_BITBOARD (QCCE_NOT_RANK_8_BITBOARD & QCCE_NOT_FILE_AB_BITBOARD)
#define QCCE_NOT_RANK_87_FILE_A_BITBOARD (QCCE_NOT_RANK_87_BITBOARD & QCCE_NOT_FILE_A_BITBOARD)
#define QCCE_NOT_RANK_87_FILE_H_BITBOARD (QCCE_NOT_RANK_87_BITBOARD & QCCE_NOT_FILE_H_BITBOARD)
#define QCCE_NOT_RANK_8_FILE_GH_BITBOARD (QCCE_NOT_RANK_8_BITBOARD & QCCE_NOT_FILE_GH_BITBOARD)
#define QCCE_NOT_RANK_1_FILE_GH_BITBOARD (QCCE_NOT_RANK_1_BITBOARD & QCCE_NOT_FILE_GH_BITBOARD)
#define QCCE_NOT_RANK_21_FILE_H_BITBOARD (QCCE_NOT_RANK_21_BITBOARD & QCCE_NOT_FILE_H_BITBOARD)
#define QCCE_NOT_RANK_21_FILE_A_BITBOARD (QCCE_NOT_RANK_21_BITBOARD & QCCE_NOT_FILE_A_BITBOARD)
#define QCCE_NOT_RANK_1_FILE_AB_BITBOARD (QCCE_NOT_RANK_1_BITBOARD & QCCE_NOT_FILE_AB_BITBOARD)
#define QCCE_NOT_RANK_8_FILE_A_BITBOARD (QCCE_NOT_RANK_8_BITBOARD & QCCE_NOT_FILE_A_BITBOARD)
#define QCCE_NOT_RANK_8_FILE_H_BITBOARD (QCCE_NOT_RANK_8_BITBOARD & QCCE_NOT_FILE_H_BITBOARD)
#define QCCE_NOT_RANK_1_FILE_H_BITBOARD (QCCE_NOT_RANK_1_BITBOARD & QCCE_NOT_FILE_H_BITBOARD)
#define QCCE_NOT_RANK_1_FILE_A_BITBOARD (QCCE_NOT_RANK_1_BITBOARD & QCCE_NOT_FILE_A_BITBOARD)

#define QCCE_WHITE_KING_SIDE_ROOK_SQUARE (1ull << 63)
#define QCCE_WHITE_QUEEN_SIDE_ROOK_SQUARE (1ull << 56)
#define QCCE_BLACK_KING_SIDE_ROOK_SQUARE (1ull << 7)
#define QCCE_BLACK_QUEEN_SIDE_ROOK_SQUARE (1ull)

QCCEBitboard QCCEGetBitboardFromSquareIndex(QCCEUint8);

QCCEBitboard QCCEGetBitboardFromSquareString(const char *);

QCCEString QCCEGetBitboardAsString(QCCEBitboard);

QCCEUint8 QCCEGetBitboardAsSquareIndex(QCCEBitboard);

QCCEString QCCEGetBitboardAsSquareString(QCCEBitboard);

void QCCEDumpBitboard(QCCEBitboard);

#endif